### ISSUE TITLE
Setup Azure Blobs for tests with large files

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/scippneutron#476]
~To Do: Can we use authentication via SciCat instead?~ -> Not fit for purpose, e.g., since files cannot be changed or removed

- Docs: https://learn.microsoft.com/en-us/azure/storage/common/storage-account-create?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=azure-portal
- "Hot" tier seems reasonable, since it has free upload/download? https://azure.microsoft.com/en-us/pricing/details/storage/blobs/
- GitHub Action: https://github.com/marketplace/actions/azure-login
- Download command probably something like `az storage blob download`?

(Johannes) At some point we discussed putting the files in `login.esss.dk:/mnt/groupdata/scipp/testdata/` instead and transferring them to the github action runner over ssh. I don't remember, why did we decide against that in the end?

**Comment by YooSunYoung** [comment]
I was trying to use azure client locally.
It'll look like this in the workflow.

```yaml
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
  
      - name: Azure Blob Download
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            az storage blob download \
              --account-name scipp \
              --account-key ${{ secrets.AZURE_ACCOUNT_KEY}} \
              --container-name nmx \
              --file pulse5_z_subset.h5 \
              --name pulse5_z_subset.h5

```


I couldn't try it in the CI since I don't have access to the github secrets...
Can someone with owner role can set up the secrets...?
